# Generated by Django 5.2.8 on 2025-11-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('school_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='director_profiles/')),
            ],
        ),
    ]
